roll =[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
name =["ram","shyaam","radha","balram","kanha","priya","siya","tina","doli","holly","molly","lal","shiv","subh","subhi"]
roll.append(30)
roll.extend([16,17])
roll.insert(2,20)
roll.remove (13)
last1 = roll.pop()
print(roll)
print(last1)
name.append("heera")
name.extend(["moti","dhoni"])
name.insert(2,"kolhi")
name.remove ("lal")
last2 = name.pop()
print(name)
print(last2)
list = ["hello","hi","tata","Bye-bye"]
print(list)
list.append(30)
list.extend(["work","done"])
list.insert(2,20)
list.remove (30)
last = list.pop()
print(list)
print(last)
